apiVersion: v1
kind: Secret
metadata:
  name: 12mas12-secret
  namespace: 12mas12
type: Opaque
data:
  rootpassword: ${{secret.ROOTPASSWORD}} | base64
  userpassword: ${{secret.USERPASSWORD}} | base64
